pablo_people_student:
    resource: "@PabloPeopleBundle/Resources/config/routing/student.yml"
    prefix:   /student

pablo_people_teacher:
    resource: "@PabloPeopleBundle/Resources/config/routing/teacher.yml"
    prefix:   /teacher

pablo_people_address:
    resource: "@PabloPeopleBundle/Resources/config/routing/address.yml"
    prefix:   /address

pablo_people_phone:
    resource: "@PabloPeopleBundle/Resources/config/routing/phone.yml"
    prefix:   /phone

pablo_people_email:
    resource: "@PabloPeopleBundle/Resources/config/routing/email.yml"
    prefix:   /email

pablo_people_comment:
    resource: "@PabloPeopleBundle/Resources/config/routing/comment.yml"
    prefix:   /comment

pablo_city_list:
    path:     /city/
    defaults: { _controller: PabloPeopleBundle:City:list }

pablo_city_json:
    path:     /city/json
    defaults: { _controller: PabloPeopleBundle:City:json }

pablo_country_list:
    path:     /country/
    defaults: { _controller: PabloPeopleBundle:Country:json }

pablo_country_json:
    path:     /country/json
    defaults: { _controller: PabloPeopleBundle:Country:json }