pablo_people_personne:
    resource: "@PabloPeopleBundle/Resources/config/routing/personne.yml"
    prefix:   /personne

pablo_people_employe:
    resource: "@PabloPeopleBundle/Resources/config/routing/employe.yml"
    prefix:   /employe

pablo_people_adresse:
    resource: "@PabloPeopleBundle/Resources/config/routing/adresse.yml"
    prefix:   /adresse

pablo_people_telephone:
    resource: "@PabloPeopleBundle/Resources/config/routing/telephone.yml"
    prefix:   /telephone

pablo_people_email:
    resource: "@PabloPeopleBundle/Resources/config/routing/email.yml"
    prefix:   /email

pablo_people_commentaire:
    resource: "@PabloPeopleBundle/Resources/config/routing/commentaire.yml"
    prefix:   /commentaire

pablo_localite_list:
    path:     /localite/
    defaults: { _controller: PabloPeopleBundle:Localite:list }

pablo_localite_json:
    path:     /localite/json
    defaults: { _controller: PabloPeopleBundle:Localite:json }

pablo_pays_list:
    path:     /pays/
    defaults: { _controller: PabloPeopleBundle:Pays:json }

pablo_pays_json:
    path:     /pays/json
    defaults: { _controller: PabloPeopleBundle:Pays:json }