pablo_user_security:
    resource: "@PabloUserBundle/Resources/config/routing/security.yml"
    prefix:   /

pablo_user_home:
    resource: "@PabloUserBundle/Resources/config/routing/home.yml"
    prefix:   /

pablo_user_profile:
    resource: "@PabloUserBundle/Resources/config/routing/profile.yml"
    prefix:   /profile

pablo_user_management:
    resource: "@PabloUserBundle/Resources/config/routing/user.yml"
    prefix:   /user