pablo_org:
    resource: "@PabloOrgBundle/Resources/config/routing.yml"
    prefix:   /

pablo_people:
    resource: "@PabloPeopleBundle/Resources/config/routing.yml"
    prefix:   /

pablo_user:
    resource: "@PabloUserBundle/Resources/config/routing.yml"
    prefix:   /

