pablo_address_list:
    path:     /
    defaults: { _controller: PabloPeopleBundle:Address:list }

pablo_address_add:
    path:     /add/{id}
    defaults: { _controller: PabloPeopleBundle:Address:add }
    requirements:
        id: \d+

pablo_address_create:
    path:     /create/{id}
    defaults: { _controller: PabloPeopleBundle:Address:create }
    requirements:
        id: \d+
        _method: post

pablo_address_edit:
    path:     /edit/{id}
    defaults: { _controller: PabloPeopleBundle:Address:edit }
    requirements:
        id: \d+

pablo_address_update:
    path:     /update/{id}
    defaults: { _controller: PabloPeopleBundle:Address:update }
    requirements:
        id: \d+
        _method: post

pablo_address_delete:
    path:     /delete/{id}
    defaults: { _controller: PabloPeopleBundle:Address:delete }
    requirements:
        id: \d+