pablo_adresse_list:
    path:     /
    defaults: { _controller: PabloPeopleBundle:Adresse:list }

pablo_adresse_add:
    path:     /add/{id}
    defaults: { _controller: PabloPeopleBundle:Adresse:add }
    requirements:
        id: \d+

pablo_adresse_create:
    path:     /create/{id}
    defaults: { _controller: PabloPeopleBundle:Adresse:create }
    requirements:
        id: \d+
        _method: post

pablo_adresse_edit:
    path:     /edit/{id}
    defaults: { _controller: PabloPeopleBundle:Adresse:edit }
    requirements:
        id: \d+

pablo_adresse_update:
    path:     /update/{id}
    defaults: { _controller: PabloPeopleBundle:Adresse:update }
    requirements:
        id: \d+
        _method: post

pablo_adresse_delete:
    path:     /delete/{id}
    defaults: { _controller: PabloPeopleBundle:Adresse:delete }
    requirements:
        id: \d+