pablo_comment_add:
    path:     /add/{id}
    defaults: { _controller: PabloPeopleBundle:Comment:add }
    requirements:
        id: \d+

pablo_comment_create:
    path:     /create/{id}
    defaults: { _controller: PabloPeopleBundle:Comment:create }
    requirements:
        id: \d+
        _method: post

pablo_comment_edit:
    path:     /edit/{id}
    defaults: { _controller: PabloPeopleBundle:Comment:edit }
    requirements:
        id: \d+

pablo_comment_update:
    path:     /update/{id}
    defaults: { _controller: PabloPeopleBundle:Comment:update }
    requirements:
        id: \d+
        _method: post

pablo_comment_delete:
    path:     /delete/{id}
    defaults: { _controller: PabloPeopleBundle:Comment:delete }
    requirements:
        id: \d+