pablo_student_list:
    path:     /{page}
    defaults: { _controller: PabloPeopleBundle:Student:list, page: 1 }
    requirements:
        page: \d+

pablo_student_search:
    path:     /search
    defaults: { _controller: PabloPeopleBundle:Student:search }
    requirements:
        _methode: post

pablo_student_show:
    path:     /show/{id}
    defaults: { _controller: PabloPeopleBundle:Student:show }
    requirements:
        id: \d+

pablo_student_edit:
    path:     /edit/{id}
    defaults: { _controller: PabloPeopleBundle:Student:edit }
    requirements:
        id: \d+

pablo_student_update:
    path:     /update/{id}
    defaults: { _controller: PabloPeopleBundle:Student:update }
    requirements:
        id: \d+
        _method: post
