pablo_teacher_list:
    path:     /{page}
    defaults: { _controller: PabloPeopleBundle:Teacher:list, page: 1 }
    requirements:
        page: \d+

pablo_teacher_search:
    path:     /search
    defaults: { _controller: PabloPeopleBundle:Teacher:search }
    requirements:
        _methode: post

pablo_teacher_show:
    path:     /show/{id}
    defaults: { _controller: PabloPeopleBundle:Teacher:show }
    requirements:
        id: \d+

pablo_teacher_edit:
    path:     /edit/{id}
    defaults: { _controller: PabloPeopleBundle:Teacher:edit }
    requirements:
        id: \d+

pablo_teacher_update:
    path:     /update/{id}
    defaults: { _controller: PabloPeopleBundle:Teacher:update }
    requirements:
        id: \d+
        _method: post