pablo_telephone_add:
    path:     /add/{id}
    defaults: { _controller: PabloPeopleBundle:Telephone:add }
    requirements:
        id: \d+

pablo_telephone_create:
    path:     /create/{id}
    defaults: { _controller: PabloPeopleBundle:Telephone:create }
    requirements:
        id: \d+
        _method: post

pablo_telephone_edit:
    path:     /edit/{id}
    defaults: { _controller: PabloPeopleBundle:Telephone:edit }
    requirements:
        id: \d+

pablo_telephone_update:
    path:     /update/{id}
    defaults: { _controller: PabloPeopleBundle:Telephone:update }
    requirements:
        id: \d+
        _method: post

pablo_telephone_delete:
    path:     /delete/{id}
    defaults: { _controller: PabloPeopleBundle:Telephone:delete }
    requirements:
        id: \d+