pablo_user_add:
    path:     /add/{id}
    defaults: { _controller: PabloUserBundle:User:add }
    requirements:
        id: \d+

pablo_user_create:
    path:     /create/{id}
    defaults: { _controller: PabloUserBundle:User:create }
    requirements:
        id: \d+
        _method: post

pablo_user_edit:
    path:     /edit/{id}
    defaults: { _controller: PabloUserBundle:User:edit }
    requirements:
        id: \d+

pablo_user_update:
    path:     /update/{id}
    defaults: { _controller: PabloUserBundle:User:update }
    requirements:
        id: \d+
        _method: post

pablo_user_enable:
    path:     /enable/{id}
    defaults: { _controller: PabloUserBundle:User:enable }
    requirements:
        id: \d+

pablo_user_delete:
    path:     /delete/{id}
    defaults: { _controller: PabloUserBundle:User:delete }
    requirements:
        id: \d+